"""initial schema

Revision ID: c6ff9d454a93
Revises: 
Create Date: 2026-07-17 21:37:49.173814+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'c6ff9d454a93'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_credentials',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('environment', sa.String(length=8), nullable=False),
    sa.Column('service', sa.String(length=32), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('secret_encrypted', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('environment', 'service', name='uq_cred_env_service')
    )
    op.create_table('app_settings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('active_environment', sa.String(length=8), nullable=False),
    sa.Column('active_strategy', sa.String(length=64), nullable=False),
    sa.Column('risk_pct', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('sleeve_weight_pct', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('sleeve_vol_target', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('leverage_cap', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False),
    sa.Column('news_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('news_time', sa.String(length=5), nullable=False),
    sa.Column('news_provider', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('environment', sa.String(length=8), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('stop_reason', sa.String(length=32), nullable=True),
    sa.Column('started_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('briefings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('briefing_date', sa.Date(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('bullets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sentiment', sa.String(length=32), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('briefing_date')
    )
    op.create_table('candles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'interval', 'open_time', name='uq_candle_key')
    )
    op.create_index('ix_candles_symbol_interval_time', 'candles', ['symbol', 'interval', 'open_time'], unique=False)
    op.create_table('equity_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('environment', sa.String(length=8), nullable=False),
    sa.Column('balance', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('month_to_date_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('sleeve_month_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('environment', 'ts', name='uq_equity_env_ts')
    )
    op.create_index('ix_equity_env_ts', 'equity_snapshots', ['environment', 'ts'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sms_status', sa.String(length=24), nullable=True),
    sa.Column('ref', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_category_ts', 'events', ['category', 'ts'], unique=False)
    op.create_index('ix_events_level_ts', 'events', ['level', 'ts'], unique=False)
    op.create_index('ix_events_ts', 'events', ['ts'], unique=False)
    op.create_table('news_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('strategies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('class_path', sa.String(length=255), nullable=False),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('validated_release', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('totp_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('withdrawal_marks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('marked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('marked_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month')
    )
    op.create_table('trades',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('entry_px', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('exit_px', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('qty', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('fees', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('funding', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('r_multiple', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('exit_reason', sa.String(length=64), nullable=True),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=8), nullable=False),
    sa.Column('bot_run_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_run_id'], ['bot_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trades_env_opened', 'trades', ['environment', 'opened_at'], unique=False)
    op.create_index('ix_trades_side', 'trades', ['side'], unique=False)
    op.create_index('ix_trades_strategy', 'trades', ['strategy'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('binance_order_id', sa.String(length=64), nullable=True),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('trade_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('qty', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('reduce_only', sa.Boolean(), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_index('ix_trades_strategy', table_name='trades')
    op.drop_index('ix_trades_side', table_name='trades')
    op.drop_index('ix_trades_env_opened', table_name='trades')
    op.drop_table('trades')
    op.drop_table('withdrawal_marks')
    op.drop_table('users')
    op.drop_table('strategies')
    op.drop_table('news_items')
    op.drop_index('ix_events_ts', table_name='events')
    op.drop_index('ix_events_level_ts', table_name='events')
    op.drop_index('ix_events_category_ts', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_equity_env_ts', table_name='equity_snapshots')
    op.drop_table('equity_snapshots')
    op.drop_index('ix_candles_symbol_interval_time', table_name='candles')
    op.drop_table('candles')
    op.drop_table('briefings')
    op.drop_table('bot_runs')
    op.drop_table('app_settings')
    op.drop_table('api_credentials')
    # ### end Alembic commands ###
